### ISSUE TITLE
Adaptive bitrate streaming transformation not working.

### ISSUE THREAD

**Issue by ravivr-dev** [cloudinary/cloudinary_dart#64]
final transformedUrl = cloudinary
        .video('DEV_ASSETS/20230518_102910')
        .transformation(
            Transformation().transcode(Transcode.streamingProfile("auto")))
        .toString();

transcode is not defined inside Transformation. and the same goes for Transcode.  It's working fine in the case of images and video.

**Comment by PixelCook** [comment]
Hey there, can you remove the toString() and try it again?

**Comment by tommyg-cld** [comment]
@ravivr-dev So that doesn't look flutter related but rather there is no predefined streaming profile called auto. When you upload a video we automatically generate a URL with sp_auto transformation per https://cloudinary.com/documentation/adaptive_bitrate_streaming#automatic_streaming_profile_selection and the chunks get generated on-the-fly.

If you want to use a pre-defined profile to pre-generate a strem then please pick one from https://cloudinary.com/documentation/adaptive_bitrate_streaming#predefined_streaming_profiles

let me know if you have any other questions.

**Comment by tommyg-cld** [comment]
@ravivr-dev it looks like we need to add support for auto profile so what you can do now is pass raw transformations via the generic() action group per https://cloudinary.com/documentation/flutter_media_transformations#passing_transformations_as_strings 

here, you would use the URL format of the transformations instead of their full name so in this case it would be something like `generic('sp_auto')`

let me know if that works?

**Comment by adimiz1** [comment]
Closing the issue, feel free to use the VideoEdit class for ABR
